# Data Update:
#   SSM Optmized AMIs
#
# This Github Action:
#   - executes the script that updates the SSM Optimized AMI's that come bundled with Moto
#   - creates a PR
#
name: "DataUpdate_SSMoptimizedAMIs"

on:
  schedule:
    - cron: '00 10 1 * *'
  workflow_dispatch:

jobs:
  update:
    name: Update SSM Optimized AMIs
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'getmoto/moto' }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: 3.9

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::682283128318:role/GithubActionsRole

    - name: Pull SSM Optimized AMIs from AWS
      run: |
        pip install boto3
        pip install moto[all]
        python scripts/ssm_get_optimized_amis.py
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        branch: 'chore-update-ssm-amis-${{ github.run_number }}'
        title: "chore: update SSM Instance AMI's"
        commit-message: "chore: update SSM Optimized AMI's"
