# Data Update:
#   SSM default parameters
#
# This Github Action:
#   - executes the script that updates the SSM default parameters that come bundled with Moto
#   - creates a PR
#
name: "DataUpdate_SSMdefaultParameters"

on:
  schedule:
    - cron: '00 12 * * 0'
  workflow_dispatch:

jobs:
  update:
    name: Update SSM default parameters
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'getmoto/moto' }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::486285699788:role/GithubActionsRole

    - name: Pull SSM default Parameters from AWS
      run: |
        pip install boto3
        pip install moto[all]
        python scripts/ssm_get_default_params.py
    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        branch: 'chore-update-ssm-params-${{ github.run_number }}'
        title: "chore: update SSM Instance parameters"
        commit-message: "chore: update SSM default parameters"
